package entity.xml;
// Generated Mar 10, 2017 8:25:27 PM by Hibernate Tools 4.3.1



/**
 * NhanVien generated by hbm2java
 */
public class NhanVien  implements java.io.Serializable {


     private int manv;
     private String hoten;
     private String diachi;
     private Boolean gioitinh;

    public NhanVien() {
    }

	
    public NhanVien(int manv) {
        this.manv = manv;
    }
    public NhanVien(int manv, String hoten, String diachi, Boolean gioitinh) {
       this.manv = manv;
       this.hoten = hoten;
       this.diachi = diachi;
       this.gioitinh = gioitinh;
    }
   
    public int getManv() {
        return this.manv;
    }
    
    public void setManv(int manv) {
        this.manv = manv;
    }
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public Boolean getGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(Boolean gioitinh) {
        this.gioitinh = gioitinh;
    }




}


